FROM nvcr.io/nvidia/pytorch:24.05-py3
WORKDIR /app
COPY requirements.txt ./
RUN apt-get update && apt-get install -y ffmpeg libgl1 libglib2.0-0 && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.txt
COPY src src
COPY telemetry.py telemetry.py
ENV OLLAMA_URL=http://localhost:11434
CMD ["python3", "src/vss_engine/gradio_frontend.py"]
