FROM nvcr.io/nvidia/pytorch:24.05-py3
WORKDIR /app
COPY requirements.asr.txt ./
RUN apt-get update && apt-get install -y ffmpeg && rm -rf /var/lib/apt/lists/*
RUN pip install --no-cache-dir -r requirements.asr.txt
COPY src/asr_server.py .
CMD ["uvicorn", "asr_server:app", "--host", "0.0.0.0", "--port", "8000"]
