version: "3.8"
services:
  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

  asr:
    build:
      context: .
      dockerfile: Dockerfile.asr
    ports:
      - "8000:8000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

  reranker:
    build:
      context: .
      dockerfile: Dockerfile.reranker
    ports:
      - "8001:8001"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

  speculative:
    build:
      context: .
      dockerfile: Dockerfile.spec
    ports:
      - "8002:8002"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "7860:7860"
    environment:
      - OLLAMA_URL=http://ollama:11434
      - ASR_URL=http://asr:8000
      - RERANKER_URL=http://reranker:8001
      - SPEC_URL=http://speculative:8002
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./data:/app/data
    depends_on:
      - ollama
      - asr
      - reranker
      - speculative
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia

volumes:
  ollama_data:
